### ISSUE TITLE
Issue with docker compose

### ISSUE THREAD

**Issue by rashuge** [synman/bambu-go2rtc#2]
When I utilize the provided docker compose file, it appears to setup the instance, but it does not actually setup a stream.  When I browse to the IP:1984 it brings up the go2rtc interface and there are no streams.  When I go to the live stream URL provided as the recommendation (making the IP change of course) it gives me a stream not found.  The only thing that I see as weird is that the go2rtc.yaml file is actually a directory using the docker compose that is provided.  The same for camera-stream.py.  They are not actual files.  They are directories instead.

**Comment by synman** [comment]
This is because I did not adapt the repo I forked container.  RTR please and feel free to submit a PR with a functional compose.

**Comment by rashuge** [comment]
`version: '3.8'
services:
  bambu-go2rtc:
    container_name: "bambu-go2rtc"
    image: "docker.io/alexxit/go2rtc"
    restart: "unless-stopped"
    # These are the configuration options if a
    # traefik setup is in place.
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.bambu-go2rtc.rule=Host(`bambu-webcam.example.com`)"
    #  - "traefik.http.routers.bambu-go2rtc.entrypoints=websecure"
    #  - "traefik.http.routers.bambu-go2rtc.tls=true"
    #  - "traefik.http.services.bambu-go2rtc.loadbalancer.server.port=1984"
    #  # This is enabling automatic LE certificate generation
    #  - "traefik.http.routers.bambu-go2rtc.tls.certresolver=leresolver"
    #  - "traefik.http.routers.bambu-go2rtc.tls.domains[0].main=bambu-webcam.example.com"
    #  # To enable basic auth uncomment and generate approprioate password using htpasswd
    #  #- "traefik.http.routers.bambu-go2rtc.middlewares=auth-$COMPOSE_PROJECT_NAME"
    #  #- "traefik.http.middlewares.auth-bambu-go2rtc.basicauth.users=bambu:$$HTPASSWD_FORMAT_PASSWORD"
    ports:
      - "1984:1984"
    environment:
      # Remember these values are defaults that can
      # be overriden by a .env file. Putting sensitive
      # data in a docker-compose.yml is less secure.
      # See env-example for the exact format.
      #PRINTER_ADDRESS: ${PRINTER_ADDRESS:-192.168.1.100}
      #PRINTER_ACCESS_CODE: ${PRINTER_ACCESS_CODE:-12345679}
    volumes:
      - "./config:/config"`

**Comment by rashuge** [comment]
Here is my docker-compose.yaml that has been updated.  It works for me.  You might want to try it.  I did have an issue with having to create the camera-stream.py and the go2rtc.yaml files manually.  I think there is something wrong with the image as it does not find the configuration files automatically.
[docker-compose.txt](https://github.com/user-attachments/files/17357133/docker-compose.txt)
